services:
  api:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command:
      - dev

  postgres:
    image: postgres:15.1
    ports:
      - '5432:5432'
    volumes:
      - './data/postgres-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=mks
      - POSTGRES_PASSWORD=mks
