name: CHECKS

on:
  push:
    branches:
      - "*"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checks
        uses: ./.github/actions/checks
      