name: Deploy production

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checks
        uses: ./.github/actions/checks
      
      - name: Install Fly CTL
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
